### ISSUE TITLE
Assert viewContains

### ISSUE THREAD

**Issue by Jhnbrn90** [svenluijten/laravel-view-assertions#2]
Hi @svenluijten 👋 

I was browsing through the code and got an idea to add an assertion for "viewContains" which could take one or multiple HTML tags and assert the view has these. 

Currently I don't have enough time to create a PR for this myself, but I can imagine that this would be a useful assertion for users of this package. 

What do you think? 

Best,

John

**Comment by svenluijten** [comment]
Interesting idea! How would that differ from using [Laravel's built-in `assertSee` method](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Testing/TestView.php#L47)?

**Comment by Jhnbrn90** [comment]
You're right 🙈 No need to reinvent the wheel. My bad 😄 👍
